### ISSUE TITLE
The source is not present in the repository

### ISSUE THREAD

**Issue by richard-whitty** [binsec/klee21-tina-artifact#1]
The project is marked as GPL 3 and has a copy of the GPL3, but in the description you say you're planning on a source release at a later point in time.

The release doesn't contain the source, the source tarball contains the contents of the repository.

If you're not ready to release it (which IMO is perfectly reasonable) maybe change the licence for the time being? At the moment it makes it impossible for anyone who conveys it to abide by the terms of the licence.

**Comment by recoules** [comment]
Hi @richard-whitty, you are right, I have just updated to the MIT license until the source release. Have a good day.
